### ISSUE TITLE
GPflow 2.5.1 install on Mac M1

### ISSUE THREAD

**Issue by timqhartnett** [GPflow/GPflow#1873] opened 2022-05-02 12:22 UTC
# Bug / performance issue / build issue
When attempting to install gpflow 2.5.1 on Mac os pip install does not recognize the install tensorflow version. I was able to install gpflow by pip installing with no dependacies and then manually installing any other packages required outside of tensorflow. this build now works fine. 

I believe the issue is basically syntax. The tensorflow package appears as tensorflow-macos when installed on macs with the M1 chip so possibly the pip dependancies don't recognize it. 

## To reproduce

pip install gpflow==2.5.1
Collecting gpflow==2.5.1
  Using cached gpflow-2.5.1-py3-none-any.whl (381 kB)
Requirement already satisfied: scipy in /Users/timhartnett/miniforge3/envs/RLBO/lib/python3.8/site-packages (from gpflow==2.5.1) (1.8.0)
Requirement already satisfied: setuptools>=41.0.0 in /Users/timhartnett/miniforge3/envs/RLBO/lib/python3.8/site-packages (from gpflow==2.5.1) (62.1.0)
Requirement already satisfied: tensorflow-probability>=0.12.0 in /Users/timhartnett/miniforge3/envs/RLBO/lib/python3.8/site-packages (from gpflow==2.5.1) (0.16.0)
Requirement already satisfied: multipledispatch>=0.6 in /Users/timhartnett/miniforge3/envs/RLBO/lib/python3.8/site-packages (from gpflow==2.5.1) (0.6.0)
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.4.0 (from gpflow) (from versions: none)
ERROR: No matching distribution found for tensorflow>=2.4.0

**Minimal, reproducible example**

```python
# This is the place for your code that reproduces the bug.
# Please make sure it does not depend on external libraries (beyond GPflow's own requirements) or specific datasets, and the smaller, the better :)
# For help on how to write a good bug report, see https://stackoverflow.com/help/minimal-reproducible-example
```

**Stack trace, or error message**
```
// Paste the full stack trace/error message here
```

## System information

* GPflow version: 
* GPflow installed from: 
* TensorFlow version: 
* Python version  
* Operating system

**Comment by jesnie** [comment] 2022-05-03 08:23
I think this is a duplicate of #1850 ?

@vdutor were you going to look into this?

**Closed by jesnie** 2022-05-03 08:23 UTC
Labels: bug
