### ISSUE TITLE
"ValueError: Cannot create a tensor proto whose content is larger than 2GB." after upgrade from 2.0.0rc1 to 2.0.0 release

### ISSUE THREAD

**Issue by clwgg** [GPflow/GPflow#1439] opened 2020-04-16 00:00 UTC
Hi,
I've been running standard GPR on a fairly large dataset using the `2.0.0rc1` version of GPflow. Since the upgrade to `2.0.0`, I'm running into the error
```
ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```
on a dataset which worked fine before.

Here is the full error message:
```
Traceback (most recent call last):
  File "main.py", line 177, in <module>
    main(args)
  File "main.py", line 64, in main
    build_allele(args)
  File "/path/to/1_model_sim/drivers.py", line 226, in build_allele
    opt_model_list(m)
  File "/path/to/1_model_sim/model.py", line 355, in opt_model_list
    m.trainable_variables)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/gpflow/optimizers/scipy.py", line 73, in minimize
    func, initial_params, jac=True, method=method, **scipy_kwargs
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 610, in minimize
    callback=callback, **options)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 345, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 295, in func_and_grad
    f = fun(x, *args)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 65, in __call__
    fg = self.fun(x, *args)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/gpflow/optimizers/scipy.py", line 95, in _eval
    loss, grad = _tf_eval(tf.convert_to_tensor(x))
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /path/to/1_model_sim/venv/lib/python3.6/site-packages/gpflow/optimizers/scipy.py:88 _tf_eval  *
        loss, grads = _compute_loss_and_gradients(closure, variables)
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/gpflow/optimizers/scipy.py:145 _compute_loss_and_gradients  *
        loss = loss_closure()
    /path/to/1_model_sim/model.py:354 None  *
        opt.minimize(lambda: - m.log_marginal_likelihood(),
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/gpflow/models/gpr.py:75 log_marginal_likelihood  *
        log_prob = multivariate_normal(Y, m, L)
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/gpflow/logdensities.py:95 multivariate_normal  *
        d = x - mu
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/ops/math_ops.py:927 r_binary_op_wrapper
        x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1314 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_conversion_registry.py:52 _default_conversion_function
        return constant_op.constant(value, dtype, name=name)
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:258 constant
        allow_broadcast=True)
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:296 _constant_impl
        allow_broadcast=allow_broadcast))
    /path/to/1_model_sim/venv/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py:522 make_tensor_proto
        "Cannot create a tensor proto whose content is larger than 2GB.")

    ValueError: Cannot create a tensor proto whose content is larger than 2GB.

```

Here are some relevant excerpts from my code:
```
m = gpf.models.GPR(data=(X, Y),
                    kernel=gpf.kernels.Exponential(active_dims = [0,1]),
                    mean_function=None)

opt = gpf.optimizers.Scipy()
opt.minimize(lambda: - m.log_marginal_likelihood(),
                m.trainable_variables)
```

I would greatly appreciate any help with this. Thanks!

**Comment by clwgg** [comment] 2020-04-16 00:25
Some more info that may or may not be relevant: I've tried this a bunch of times with the same dataset and others of similar size, on different machines, with either version of GPflow (using the same versions of dependencies) and the error occurs reliably in `2.0.0` and `2.0.1`, but not in `2.0.0rc1`. Unfortunately I'm not very familiar yet with the GPflow codebase (or tensorflow), so I have a hard time figuring out what may induce this behavior. Versions of other relevant packages are:
```
protobuf               3.11.3
tensorflow             2.1.0
tensorflow-estimator   2.1.0
tensorflow-probability 0.9.0

```

**Comment by st--** [comment] 2020-04-16 10:29
Hi @clwgg, thanks for reporting this! Can you make a minimal example that reproduces this bug (e.g. using `X, Y = np.random.randn(num_data, input_dim), np.random.randn(num_data, output_dim)` to make a sufficiently large data set? Off the top of my head I can't think of anything that changed from rc1 to the 2.0.0 release that would have changed this - so any further help you can give us in narrowing it down would be good :)

**Comment by clwgg** [comment] 2020-04-16 23:36
Yes, absolutely! The code snippet below reproduces the behavior I report above: it runs fine on `2.0.0rc1`, but throws the error on `2.0.0`.

I should add that I run these analyses on CPU on a machine with 128 GB of RAM.

```
import numpy as np

import tensorflow as tf
import gpflow as gpf
import tensorflow_probability as tfp
from gpflow.utilities import print_summary

gpf.config.set_default_positive_minimum(1e-7)

X, Y = np.random.random((2000, 2)), np.random.random((2000, 200000))

m = gpf.models.GPR(data=(X, Y),
                        kernel=gpf.kernels.Exponential(active_dims = [0,1]),
                                            mean_function=None)

print_summary(m)

opt = gpf.optimizers.Scipy()
opt.minimize(lambda: - m.log_marginal_likelihood(),
                    m.trainable_variables)

print_summary(m)
```

**Comment by st--** [comment] 2020-04-17 17:06
Thank you. Thanks to `git bisect`, it looks like the offending commit is 426f6d2b74e3e46604241de91a16896df193a609: Add jit flag to gpflow.optimizers.Scipy (#1190).
We since renamed the flag to `compile`, and indeed if you change your example as follows:
```diff
-opt.minimize(lambda: - m.log_marginal_likelihood(),
-                    m.trainable_variables)
+opt.minimize(m.training_loss,
+                    m.trainable_variables, compile=False)
```
then it also works in the latest 2.0.1 release and on the develop branch. You can manually reintroduce the bug by explicitly wrapping the training objective in `tf.function()`:
```python
objective = tf.function(m.training_loss)
opt.minimize(objective, m.trainable_variables, compile=False)
```
The underlying reason is that the compilation by `tf.function()` adds all constants into the graph - in this case this includes the data (X, Y) stored on the model. And the graph's size is capped... So it's an unfortunate interaction between TensorFlow internals and how GPflow makes use of TensorFlow.
Simply *not* using tf.function() can make your code significantly slower than it needs to be when e.g. the model objective gets called many times throughout the hyperparameter optimization. I think it *might* make a difference if you convert the data to tf.Tensor objects first: can you try the following change in your (actual) code:
```diff
-m = gpf.models.GPR(data=(X, Y),
-                        kernel=gpf.kernels.Exponential(active_dims = [0,1]),
-                                            mean_function=None)
+m = gpf.models.GPR(data=(tf.convert_to_tensor(X), tf.convert_to_tensor(Y)),
+                        kernel=gpf.kernels.Exponential(active_dims = [0,1]),
+                                            mean_function=None)
```
? Let me know if that solves your problem and then we can think what we can do to make GPflow work better out of the box.

**Comment by awav** [comment] 2020-04-17 18:46
Thanks, @st-- for investigating this issue! Indeed, Protobuf (the way how TF graph is represented) has a hard limit in 2GB, details here https://stackoverflow.com/a/51473218/7788672.

@clwgg, the rule of thumb would be using TF tensors as much as possible and minimizing NumPy and TensorFlow interactions.

**Comment by clwgg** [comment] 2020-04-18 02:30
I can confirm that wrapping the data input to `GPR` in `tf.convert_to_tensor()` fixes the issue I report. Thanks a lot @st-- for your help with this!

**Comment by st--** [comment] 2020-04-18 12:14
I don't understand why tf.function can't just convert the numpy arrays to tensors itself! So I shall blame it on them, it's not exactly our own bug. Still, we shouldn't have gpflow users suffer!
As a work-around for this bug, I think we should just change the models to explicitly convert from numpy arrays to tensors in the `data` argument to the model constructors. @awav what do you think? any other/better ideas?

**Comment by awav** [comment] 2020-04-20 10:17
I don't think we can classify it as a bug :) It is a special and unpleasant "feature". Anyway, it might change in TF2.2. @st--, If you don't mind I will test it on TF2.2 and make a PR with `tf.convert_to_tensor` in models.

**Comment by st--** [comment] 2020-04-20 15:43
I would consider "Doesn't behave as [reasonably] expected" as a bug - if we had clearly stated "do not pass numpy arrays as data to model constructors", it'd be different, but in fact the notebooks all use this pattern. Thanks for looking into it! I'll assign this issue to you then. By when do you think you'll be able to get to it?

**Comment by awav** [comment] 2020-04-21 09:49
> I would consider "Doesn't behave as [reasonably] expected" as a bug

I was sarcastic :)

> By when do you think you'll be able to get to it?

Wednesday, 22 Apr.

**Closed** 2020-05-07 12:22 UTC
Labels: bug

**Comment by st--** [comment] 2020-05-07 15:22
Hi @clwgg , thanks for helping us discover this issue - it's fixed in the latest 2.0.2 release!

**Comment by clwgg** [comment] 2020-05-07 15:24
Wonderful, thank you!

**Comment by st--** [comment] 2020-05-07 21:34
(And of course if it doesn't resolve your issue after all, please reopen it!)
