### ISSUE TITLE
MLP kernel gradients

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#409] opened 2017-05-03 09:03 UTC
Hi all, (specifically @mrksr, since you did the PR :) )

I'm trying to use the MLP kernel, but I get nans in the gradients! Has anybody used them before (i.e. am I doing something wrong?) or is there a bug?

```python
import numpy as np
import GPflow
X = np.random.rand(4, 1)
Y = np.random.randn(X.shape[0])[:, None] * 0.1 + np.sum(np.sin(3*X), 1)[:, None]
full = GPflow.gpr.GPR(X, Y, GPflow.kernels.ArcCosine(X.shape[1]))
full._compile()
print(full._objective(full.get_free_state())[1])
```

Output: `[ 0.81873344         nan         nan  0.25598061]`

**Comment by mrksr** [comment] 2017-05-03 09:20
If I alter your example to be reproducable:
```python
import numpy as np
import GPflow

rng = np.random.RandomState(23)
X = rng.rand(4, 1)
Y = rng.randn(X.shape[0])[:, None] * 0.1 + np.sum(np.sin(3*X), 1)[:, None]
full = GPflow.gpr.GPR(X, Y, GPflow.kernels.ArcCosine(X.shape[1]))
full._compile()
print(full._objective(full.get_free_state())[1])
```
my result using float64 is `[        nan  0.22290395         nan  0.81633098]`.

My first guess would be that the culprit is the `acos`-operation and indeed, If I apply this patch:
```patch
diff --git a/GPflow/kernels.py b/GPflow/kernels.py
index 36adb26..a9f12b9 100644
--- a/GPflow/kernels.py
+++ b/GPflow/kernels.py
@@ -573,10 +573,11 @@ class ArcCosine(Kern):
             X2_denominator = tf.sqrt(self._weighted_product(X2))

         numerator = self._weighted_product(X, X2)
+        acos_bound = 1 - settings.numerics.jitter_level
         theta = tf.acos(tf.clip_by_value(numerator / \
                                          X_denominator[:, None] / \
                                          X2_denominator[None, :],
-                                         -1., 1.))
+                                         -acos_bound, acos_bound))

         return self.variance * (1. / np.pi) * self._J(theta) * \
                X_denominator[:, None] ** self.order * \
```
the result becomes `[-0.01297854  0.22256484  0.01297854  0.81661298]`. Could you check if this fixes the issue? If so, we can maybe come up with a better way of handling the `nan`s.

**Comment by markvdw** [comment] 2017-05-03 11:18
Yes, that fixes it exactly! This definitely saved me a lot of time, so thanks!

A quick `tf.Print()` confirms that the calculated value becomes epsilon larger than 1. Is this calculation technically guaranteed to be below 1? The issue with clipping is that it removes gradient information, although there is probably little gradient left at these values. What would be an elegant way to solve this?

**Comment by mrksr** [comment] 2017-05-03 11:40
Analytically, the value of the calculation should be the cosine of an angle (since it is calculating the scalar product of two unit vectors) and therefore be guaranteed to have an absolute value of at most one. What we are seeing here should be numerical differences. I am quite surprised that a clip with -1 and 1 returns values outside of the range.
Besides the gradient problem, a clip is quite close to what we need: It should be fine to simply saturate the values at -1 and 1. A logistic function might be a possible solution, but that could be overkill?

**Comment by markvdw** [comment] 2017-05-03 12:25
Yeah, it's a floating point issue... These things are pretty brittle sometimes. A clip is probably fine for now. Do you want to submit a patch, or should I?

**Comment by jameshensman** [comment] 2017-05-03 12:28
One way to get around clipping is to 'squash' the values: x = 1e-6 +
(1-2e-6) * x. This retains the gradient.

**Comment by mrksr** [comment] 2017-05-03 12:40
Sounds good, I will create a PR with the solution @jameshensman suggested.

**Comment by markvdw** [comment] 2017-05-03 12:51
Thanks a lot, it's so great to be able to get fast responses for these things!

**Comment by mrksr** [comment] 2017-06-22 08:24
I just realized this issue ist still open. Do you consider #411 a fix, @markvdw, would you like me to improve this PR in some way?

**Comment by jameshensman** [comment] 2017-06-22 08:49
#411 is merged, so I think the only action needed is to close this PR.

**Closed by jameshensman** 2017-06-22 08:49 UTC
