### ISSUE TITLE
Saving and restoring models from file

### ISSUE THREAD

**Issue by doktorneergaard** [GPflow/GPflow#753] opened 2018-05-10 17:30 UTC
What is the current best practices for saving and restoring trained models?

I have initialized and optimized some models based on the following snippet:

```python
m = gpf.models.SVGP(X, y.reshape((-1, 1)), kern=gpf.kernels.RBF(len(selected_features)), likelihood=gpf.likelihoods.Gaussian, Z=inductionPoints)
gpf.train.ScipyOptimizer().minimize(m, maxiter=1000)
```
And then pickled the optimized model:
```python
with open('/path/to/file', 'wb') as fp:
    pickle.dump(m.read_trainables(), fp)
```

But then I want to use the model for prediction later on. I am using the following
```python
with open('/path/to/file', 'rb') as fp:
    param_dict = pickle.load(fp)
m = gpf.models.SVGP(X, y.reshape((-1, 1)), kern=gpf.kernels.RBF(len(selected_features)), likelihood=gpf.likelihoods.Gaussian, Z=inductionPoints)
m.assign(param_dict)
```
Is there any way to use the assign method without specifying the arguments again? It seems kind of clunky that I have to have access to exactly the same variables as for the training, especially also if the induction points have been shuffled. Am I missing something, or is this not the way to do it?

**Comment by markvdw** [comment] 2018-05-10 18:10
With "without specifying the arguments again" you mean in the constructor of `SVGP`?

Unfortunately, you're right. The way you're doing is the best way. It's also the way that I do it whenever I need to store models. The problem is that we don't want to have to store the structure of all the objects in the `SVGP` instance when we store the parameters. This would be clunky, easy to break and wouldn't compatible with code changes.

Just out of interest though, how would you like to see it being done?

**Comment by doktorneergaard** [comment] 2018-05-10 18:45
@markvdw Yes, I mean the arguments to the constructor, ie. I don't want to specify X, y, Z, etc. I really don't see why they should be relevant for further use, or maybe I am not understanding correctly what the GP model has to use for future predictions. It is my understanding that the hyperparameters would be sufficient?

So, the way I would prefer it is something akin to the API in scikit-learn: first, assign the constructor to an object, then fit/optimize the model using supplied datapoints, and then after that use the optimized model for prediction or save the model for later use:
```python
# Initialize the model
GPmodel = gpf.models.SVGP(kern=kernel_fn, likelihood=likelihood_fn, kwargs)

# Fit/optimize over supplied datapoints
GPmodel.optimize(X_train, y_train, maxiter=maxiter, optimizer=optimization_fn)

# Now, internally, the model contains optimized hyperparameters and can be used to predict on new data
predictions = GPmodel.predict(X_test)

# We can also save the model
GPmodel.save_to_file('/path/to/save/file')
```

And in a separate session, we would be able to call the model from the save file and it would contain exactly the same hyperparameters, likelihoods, priors, etc. as before:
```python
GPmodel = gpf.models.restore('/path/to/save/file')
predictions_restored_model = GPmodel.predict(X_test)
```

Does that make sense?

**Comment by doktorneergaard** [comment] 2018-05-10 20:43
@markvdw A small update: I'm running into some errors with the above code. Whenever I try to assign model parameters, I get the following:
```python
Traceback (most recent call last):
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-01aaaf39abc2>", line 2, in <module>
    likelihood=gpf.likelihoods.Gaussian, Z=X.copy())
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/gpflow-1.1.1-py3.6.egg/gpflow/core/compilable.py", line 90, in __init__
    self.build()
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/gpflow-1.1.1-py3.6.egg/gpflow/core/node.py", line 156, in build
    self._build()
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/gpflow-1.1.1-py3.6.egg/gpflow/models/model.py", line 79, in _build
    likelihood = self._build_likelihood()
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/gpflow-1.1.1-py3.6.egg/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/gpflow-1.1.1-py3.6.egg/gpflow/models/svgp.py", line 118, in _build_likelihood
    var_exp = self.likelihood.variational_expectations(fmean, fvar, self.Y)
  File "/home/neergaard/anaconda3/envs/gpflow/lib/python3.6/site-packages/gpflow-1.1.1-py3.6.egg/gpflow/decors.py", line 64, in tensor_mode_wrapper
    'Tensor mode works only for Parameterized object.')
gpflow.core.errors.GPflowError: Tensor mode works only for Parameterized object.
```

**Comment by markvdw** [comment] 2018-05-11 09:43
Yes that totally makes sense. For predictions only the hyperparameters and variational parameters are needed (so Z definitely is needed for predictions, but not X and Y). The reason that we require to supply X and Y as inputs to construct a model is a hangover from the full GP. In the full GP (or `GPR` in GPflow), you need the hyperparameters _and_ the data in order to make predictions. For sparse GPs this is no longer necessary, but we decided to keep a similar interface (other GP packages made the same choice).

Anyway, there are some vague plans to make something like a VariationalPosterior object, which only requires hyper and variational parameters for predictions, so you don't have to keep the data around (or pass in data). However we currently explicitly choose not to support something like:
```
GPmodel = gpf.models.restore('/path/to/save/file')
predictions_restored_model = GPmodel.predict(X_test)
```
For the reason that this `restore()` function would have to re-create all the kernel and likelihood objects. It is very hard to store the object hierarchy in a general way, especially as versions of the code change, and since we're moving to much more complex models.

**Comment by markvdw** [comment] 2018-05-11 09:45
Thinking about it a bit more, actually, perhaps there would be a neat way to do this, but it's not something we're actively developing at the moment. Obviously, we're happy to accept contributions, although for a feature this big and important, we would recommend having a few calls beforehand to discuss software design etc.

**Comment by awav** [comment] 2018-05-11 10:29
Hello @doktorneergaard, @markvdw 

```
import gpflow
import numpy as np
import numpy.random as rnd
rnd.randn(100, 1)
Y = np.sin(X) + np.sin(1.5*X) + 0.3 * rnd.randn(*X.shape)
m = gpflow.models.SGPR(X, Y, gpflow.kernels.RBF(1), Z=X.copy())
gpflow.train.ScipyOptimizer().minimize(m, maxiter=10)
saver= gpflow.saver.Saver()
saver.save('/tmp/model', m)
m.read_trainables()['SGPR/kern/variance']
> array(2.64659385)
```

next session:

```
m =  gpflow.saver.Saver().load('/tmp/model')
m.read_trainables()['SGPR/kern/variance']
> 2.64659385
```

PS: @doktorneergaard, could you post next time MWE, so that we could copy&paste your code. Thank you!

**Comment by markvdw** [comment] 2018-05-11 13:26
What?! This is amazing! I didn't even know that we had this!

**Comment by doktorneergaard** [comment] 2018-05-11 15:52
@markvdw No worries, thank you for your detailed responses!
@awav This is exactly what I needed, thank you!. Tested and works for my purpose. Sorry for not posting a proper MWE.
@markvdw, @markvdw This would be great to have in the documentation!

**Closed** 2018-05-11 16:09 UTC
