### ISSUE TITLE
Save model to file for reuse

### ISSUE THREAD

**Issue by dgilford** [GPflow/GPflow#852] opened 2018-09-14 13:28 UTC
Hello,

I've been digging through the archive here and come across several discussions on saving and restoring a GPflow model (m) (e.g. #753, #689, #543). I can't seem to get the various methods discussed to work myself. I want to save the model so that I don't have to reoptimize every time I want to sample from the model in a new session (the particular problem I care about takes about 35 minutes to optimize as I have a lot of data points).

I'm running with python 3.5.2, on a Jupyter notebook for save and restore (each separate), and I cloned the repository on 5/31/18.
Here is an example code that I have been working with:

Save:

~~~
import gpflow
import numpy as np
import random
import tensorflow as tf

rng = np.random.RandomState(4)
X = rng.uniform(0, 5.0, 15)[:, np.newaxis]
Y = np.sin((X[:, 0] - 2.5) ** 2).reshape(len(X),1)

with gpflow.defer_build():
    k = gpflow.kernels.Matern32(1)+gpflow.kernels.RBF(1)
    m = gpflow.models.GPR(X, Y, kern=k,name='model')
    m.likelihood.variance = 1e-03
    m.likelihood.trainable = False
    
tf.local_variables_initializer()
tf.global_variables_initializer()

tf_session = m.enquire_session()
m.compile( tf_session )

gpflow.train.ScipyOptimizer().minimize(m)

saver = tf.train.Saver()
save_path = saver.save(tf_session, "./model.ckpt")
print("Model saved in path: %s" % save_path)
~~~

and restore:

~~~
import gpflow
import numpy as np
import random
import tensorflow as tf

rng = np.random.RandomState(4)
X = rng.uniform(0, 5.0, 15)[:, np.newaxis]
Y = np.sin((X[:, 0] - 2.5) ** 2).reshape(len(X),1)
    
with gpflow.defer_build():
    k = gpflow.kernels.Matern32(1)+gpflow.kernels.RBF(1)
    m = gpflow.models.GPR(X, Y, kern=k)
    m.likelihood.variance = 1e-03
    m.likelihood.trainable = False
    
tf.local_variables_initializer()
tf.global_variables_initializer()

tf_graph = m.enquire_graph()
tf_session = m.enquire_session()
m.compile( tf_session )

saver = tf.train.Saver()

save_path = saver.restore(tf_session, "./model.ckpt")
print("Model loaded from path: %s" % save_path)
~~~

The error I am getting for this method is:
`NotFoundError: Key GPR-2f9a4138-12/X/dataholder not found in checkpoint`

I also tried to implement the saver, (https://github.com/GPflow/GPflow/blob/fd6beaafd27c5c48d09f037b1b46f56260da424c/gpflow/saver/saver.py) and it didn't work for me. But I noticed discussion elsewhere that hinted maybe this isn't supported anymore?

Thanks for any help you can provide in advance, and sorry that I'm asking a redundant question.

**Comment by st--** [comment] 2018-09-14 15:10
In the code snippet that restores the model, you are missing the `name='model'` part - does it work if you add that? (Your code would be more robust if you have a single function that builds the model both for optimising/saving and restoring/predicting, which you then import in both parts)

**Comment by dgilford** [comment] 2019-02-05 17:12
I never got a chance to come back to this. Sorry about that @st-- 

I add `name='model'` as suggested to the restore code and it "works" in the sense that I don't get the same error any more, but now I have a different problem.

When I inquire of the restored model what its parameters are, they remain the untrained/not optimized versions, which is not the behavior I am looking for.

**Comment by st--** [comment] 2019-02-06 15:49
Huh, looks like there's an issue with the restore not actually anchoring the tensorflow values to the numpy view: if you print `m.kern.kernels[0].lengthscales.value`, you get the default of 1.0, if you print `m.kern.kernels[0].lengthscales.read_value(tf_session)`, it prints the correct value (9.292... for me). After calling `m.anchor(tf_session)`, then `m.kern.kernels[0].lengthscales.value` works as intended, as well.

This is an intricacy of how tensorflow graphs&sessions work ... @awav, is there any reason why we can't make the saver.restore() call the anchor() as well ?

**Comment by dgilford** [comment] 2019-02-06 16:17
Thanks for following up @st-- , I really appreciated it!

I'm giving this a try with:
`m.anchor(tf_session)
m.as_pandas_table()`
And I also see the same hyperparameter value for `m.kern.kernels[0].lengthscales.value` (9.292...), so that's a good sign. It seems to be working now.

I'm wanting to construct a workflow that is repeatable and reliable for saving/loading, should I just go through these steps?:
1) create/optimize the model
2) set `tf.global_variables_initializer()`
3) create the saver
4) save the session
5) reconstruct the model
6) create the saver
7) restore the session
8) call `m.anchor(tf_session)`

Trying to figure out what is the bare minimum in the code I made above to get the expected behavior. My relative unfamiliarity with Tensorflow means its difficult for me to judge which parts are useful (I copied much of it from previous examples that people had reported).

**Comment by st--** [comment] 2019-02-06 22:17
Looks about right, though you don't need to optimize the variables after creating the model (if anything, that is something I suspect you'd do *before* optimizing!) - your example works just fine without the initializer calls. So, (1. 3. 4.) / (5. 6. 7. 8.) :)

**Comment by st--** [comment] 2019-12-03 21:39
Closing this as we'll no longer actively maintain gpflow pre-2.0 - if you care about getting this fixed in the 1.x release branch, please make a PR.

**Closed by st--** 2019-12-03 21:39 UTC
Labels: gpflow-v1
